# This is a yml file in which we provide descriptions for both models and columns.
# You can see how we also apply doc blocks (https://docs.getdbt.com/docs/building-a-dbt-project/documentation#using-docs-blocks) to 
# write descriptions in one place (via a md file) and apply them through the project.
# We have also applied tests to every primary key listed in this file.
# Full documentation: https://docs.getdbt.com/reference/declaring-properties

version: 2

models:
  - name: BIRD_STRIKES_CURATION
    description: rename and format bird strikes data
    columns:
      - name: record_id
        description: "primary key of the strike records"
        tests:
          - unique
          - not_null
      - name: aircraft_type
        description: "the type of aircraft such as airplane"
        tests:
      - name: airport_name
        description: "name of aircraft"
        tests:
      - name: altitude_bin
        description: "the range of alititude such as (>1000 ft/<1000 ft)"
        tests:
      - name: aircraft_model
        description: "ID issued by a civil aircraft when it is registered with the civil aviation management agency."
        tests:
      - name: wildlife_struck
        description: "the range of number of wildlife struck (1/2-10/over 100)"
        tests:
      - name: wildlife_struck_actual
        description: "the actual number of wildlife struck"
        tests:
      - name: flight_impact
        description: impact to flight such as "engine shut down" 
        tests:
      - name: flight_date
        description:  the date of flight
        tests:
      - name: indicated_damage
        description:  effect of flight indicated damage
        tests:
          - accepted_values:
              values: ['No damage','Caused damage']
      - name: airline_operator
        description: "airline operating agency or company"
        tests:
      - name: origin_state
        description: "state from which the airplane departs"
        tests:
      - name: flight_phase
        description: "phase of flight such as:landing/take off/approach"
        tests:
      - name: precipitation
        description: whether it rained that day
        tests:
      - name: wildlife_collected
        description: remains of wildlife were collected
        tests: 
          - accepted_values:
              values: ['TRUE','FALSE']
      - name: wildlife_sent
        description: remains of wildlife sent to Smithsonian
        tests: 
          - accepted_values:
              values: ['TRUE','FALSE']  
      - name: remarks
        description: some comments of bird strike
        tests:
      - name: wildlife_size
        description: size of wildlife such as:small/medium/large
        tests:
      - name: sky_condition
        description: weather conditions such as:no cloud
        tests:
      - name: wildlife_species
        description: species of wildlife
        tests:
      - name: pilot_warned
        description: did the pilot warn the bird
        tests: 
          - accepted_values:
              values: ['Y','N']
      - name: total_cost
        description: economic loss caused by the bird strike
        tests:
      - name: ground_feet
        description: flight height above ground
        tests:
      - name: people_injured
        description: number of people get injuried
        tests:
      - name: large_aircraft
        description: is this airplane large
        tests: 
          - accepted_values:
              values: ['Yes','No'] 
      - name: aircraft_engines
        description:  how many engines does this airplane have
        tests:
      - name: filename
        description: current record from which file 
        tests:
          